version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - database

  database:
    image: mysql:latest
    volumes:
      - ./data:/data
